2023 U1 Python kodas
Dovias/IT-Egzaminai pull request #3
Opened 2024-04-07 17:38 UTC by kornelijusp

2024-04-08 10:11 UTC, Dovias commented
Pabaik arba išimk U2 WIP failus ir tada sumerge'insiu

2024-04-08 10:13 UTC, Dovias requested changes

2024-04-08 10:13 UTC, Dovias commented on IT-VBE-2023/Python/U2.py
WIP nedėk failų

2024-04-08 10:13 UTC, Dovias commented on IT-VBE-2023/Python/U2.txt
WIP nedėk failų

2024-04-08 10:13 UTC, Dovias commented on IT-VBE-2023/Python/U2rez.txt
WIP nedėk failų

2024-04-08 20:07 UTC, kornelijusp reviewed
ok

2024-04-08 20:12 UTC, kornelijusp reviewed
Ištrinta

2024-04-15 01:00 UTC, Dovias approved these changes

2024-04-15 01:00 UTC, merged